config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :theme_versions
  resources :themes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/theme.rb
class Theme < ApplicationRecord

  has_many :theme_versions
  
end

app/models/theme_version.rb
class ThemeVersion < ApplicationRecord
  mount_uploader :theme_file, ThemeFileUploader

  belongs_to :theme
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/controllers/theme_versions_controller.rb
class ThemeVersionsController < ApplicationController
  before_action :set_theme_version, only: [:show, :edit, :update, :destroy]

  skip_before_action :authenticate_user!, only: :show

  # GET /theme_versions
  # GET /theme_versions.json
  def index
    @theme_versions = ThemeVersion.all
  end

  # GET /theme_versions/1
  # GET /theme_versions/1.json
  def show
  end

  # GET /theme_versions/new
  def new
    @theme_version = ThemeVersion.new
  end

  # GET /theme_versions/1/edit
  def edit
  end

  # POST /theme_versions
  # POST /theme_versions.json
  def create
    @theme_version = ThemeVersion.new(theme_version_params)

    respond_to do |format|
      if @theme_version.save
        format.html { redirect_to @theme_version, notice: 'Theme version was successfully created.' }
        format.json { render :show, status: :created, location: @theme_version }
      else
        format.html { render :new }
        format.json { render json: @theme_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /theme_versions/1
  # PATCH/PUT /theme_versions/1.json
  def update
    respond_to do |format|
      if @theme_version.update(theme_version_params)
        format.html { redirect_to @theme_version, notice: 'Theme version was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme_version }
      else
        format.html { render :edit }
        format.json { render json: @theme_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theme_versions/1
  # DELETE /theme_versions/1.json
  def destroy
    @theme_version.destroy
    respond_to do |format|
      format.html { redirect_to theme_versions_url, notice: 'Theme version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme_version
      @theme_version = ThemeVersion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theme_version_params
      params.require(:theme_version).permit(:theme_id, :version, :details, :theme_file)
    end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  skip_before_action :authenticate_user!, only: :show

  # GET /themes
  # GET /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: 'Theme was successfully created.' }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to @theme, notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to themes_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theme_params
      params.require(:theme).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/theme_versions_helper.rb
module ThemeVersionsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThemeChecker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/theme_versions/_form.html.erb
<%= form_with(model: theme_version, local: true) do |form| %>
  <% if theme_version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(theme_version.errors.count, "error") %> prohibited this theme_version from being saved:</h2>

      <ul>
      <% theme_version.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :theme_id %>
    <%= form.select :theme_id, options_for_select(Theme.pluck(:name, :id)), {id: :theme_version_theme_id} %>
  </div>

  <div class="field">
    <%= form.label :version %>
    <%= form.text_field :version, id: :theme_version_version %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_area :details, id: :theme_version_details %>
  </div>

  <div class="field">
    <%= form.label :theme_file %>
    <%= form.file_field :theme_file, id: :theme_version_theme_file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/theme_versions/edit.html.erb
<h1>Editing Theme Version</h1>

<%= render 'form', theme_version: @theme_version %>

<%= link_to 'Show', @theme_version %> |
<%= link_to 'Back', theme_versions_path %>

app/views/theme_versions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Theme Versions</h1>

<table>
  <thead>
    <tr>
      <th>Theme</th>
      <th>Version</th>
      <th>Details</th>
      <th>Theme file</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @theme_versions.each do |theme_version| %>
      <tr>
        <td><%= theme_version.theme.name %></td>
        <td><%= theme_version.version %></td>
        <td><%= theme_version.details %></td>
        <td><%= link_to 'Download', theme_version.theme_file.url %></td>
        <td><%= link_to 'Show', theme_version %></td>
        <td><%= link_to 'Edit', edit_theme_version_path(theme_version) %></td>
        <td><%= link_to 'Destroy', theme_version, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Theme Version', new_theme_version_path %>

app/views/theme_versions/new.html.erb
<h1>New Theme Version</h1>

<%= render 'form', theme_version: @theme_version %>

<%= link_to 'Back', theme_versions_path %>

app/views/theme_versions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Theme:</strong>
  <%= @theme_version.theme.name %>
</p>

<p>
  <strong>Version:</strong>
  <%= @theme_version.version %>
</p>

<p>
  <strong>Details:</strong>
  <%= @theme_version.details %>
</p>

<p>
  <strong>Theme file:</strong>
  <%= @theme_version.theme_file %>
</p>

<%= link_to 'Edit', edit_theme_version_path(@theme_version) %> |
<%= link_to 'Back', theme_versions_path %>

app/views/themes/_form.html.erb
<%= form_with(model: theme, local: true) do |form| %>
  <% if theme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

      <ul>
      <% theme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :theme_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/themes/edit.html.erb
<h1>Editing Theme</h1>

<%= render 'form', theme: @theme %>

<%= link_to 'Show', @theme %> |
<%= link_to 'Back', themes_path %>

app/views/themes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Themes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @themes.each do |theme| %>
      <tr>
        <td><%= theme.name %></td>
        <td><%= link_to 'Show', theme %></td>
        <td><%= link_to 'Edit', edit_theme_path(theme) %></td>
        <td><%= link_to 'Destroy', theme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Theme', new_theme_path %>

app/views/themes/new.html.erb
<h1>New Theme</h1>

<%= render 'form', theme: @theme %>

<%= link_to 'Back', themes_path %>

app/views/themes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @theme.name %>
</p>

<%= link_to 'Edit', edit_theme_path(@theme) %> |
<%= link_to 'Back', themes_path %>